language: android

jdk:
  - openjdk6

android:
  components:
    - build-tools-21.1.0
    - android-21

script:
  - ./gradlew check --stacktrace

after_success:
- ./gradlew jacocoTestReport coveralls
